services:
  user-web:
    container_name: user-web-service
    build:
      context: .
      dockerfile: user/Dockerfile
    ports:
      - '10001:8081'
    restart: 'no'
    labels:
      project: "apapedia"
    networks:
      - backend-network
    env_file:
      - user/.env
    platform: linux/amd64
  catalog-web:
    container_name: catalog-web-service
    build:
      context: .
      dockerfile: catalog/Dockerfile
    ports:
      - '10002:8082'
    restart: 'no'
    labels:
      project: "apapedia"
    networks:
      - backend-network
    env_file:
      - catalog/.env
    platform: linux/amd64
  order-web:
    container_name: order-web-service
    build:
      context: .
      dockerfile: order/Dockerfile
    ports:
      - '10003:8083'
    restart: 'no'
    labels:
      project: "apapedia"
    networks:
      - backend-network
    env_file:
      - order/.env
    platform: linux/amd64
networks:
  backend-network:
    name: db-backend-network
    external: true