services:
  user-web:
    container_name: user-web-service
    build:
      context: .
      dockerfile: user/Dockerfile
    ports:
      - '10001:8081'
    restart: 'no'
    labels:
      project: "apapedia"
    networks:
      - backend-network
    env_file:
      - user/.env
    platform: linux/amd64
networks:
  backend-network:
    name: db-backend-network
    external: true